/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tetrisched_CONSTANTS_H
#define tetrisched_CONSTANTS_H

#include "tetrisched_types.h"

namespace alsched {

class tetrischedConstants {
 public:
  tetrischedConstants();

};

extern const tetrischedConstants g_tetrisched_constants;

} // namespace

#endif
