/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tetrisched_constants.h"

namespace alsched {

const tetrischedConstants g_tetrisched_constants;

tetrischedConstants::tetrischedConstants() {
}

} // namespace

